@BaseUrl=http://localhost:8000/api
@Token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJEb3RuZXRDYW1lcm9vbiIsImlzcyI6IkRvdG5ldENhbWVyb29uIiwiZXhwIjoxNzM1OTAwNDU1LCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiNGVhYjc3NTQtYTZiMS00OTczLTg2MjEtMDYxZWNjZWZlYzkwIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiI0ZWFiNzc1NC1hNmIxLTQ5NzMtODYyMS0wNjFlY2NlZmVjOTAiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBcHBsaWNhdGlvbiIsImlhdCI6MTczNTg5Njg1NSwibmJmIjoxNzM1ODk2ODU1fQ.vTn1m-cT_e4HifyeRqFUWoXTcyJIWEwWoyfnEMPsJ3n1oebPrQNiWG-pJTuv8ohFn86AlMi63VvACy_DEbG08g

GET {{BaseUrl}}/projects
Authorization: Bearer {{Token}}
