/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartnersIndexRouteImport } from './routes/partners/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as AppsIndexRouteImport } from './routes/apps/index'
import { Route as EventsNewRouteImport } from './routes/events/new'
import { Route as AppsRegisterRouteImport } from './routes/apps/register'
import { Route as EventsIdEditRouteImport } from './routes/events/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersIndexRoute = PartnersIndexRouteImport.update({
  id: '/partners/',
  path: '/partners/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRegisterRoute = AppsRegisterRouteImport.update({
  id: '/apps/register',
  path: '/apps/register',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdEditRoute = EventsIdEditRouteImport.update({
  id: '/events/$id/edit',
  path: '/events/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps/register': typeof AppsRegisterRoute
  '/events/new': typeof EventsNewRoute
  '/apps/': typeof AppsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/partners/': typeof PartnersIndexRoute
  '/events/$id/edit': typeof EventsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps/register': typeof AppsRegisterRoute
  '/events/new': typeof EventsNewRoute
  '/apps': typeof AppsIndexRoute
  '/events': typeof EventsIndexRoute
  '/partners': typeof PartnersIndexRoute
  '/events/$id/edit': typeof EventsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apps/register': typeof AppsRegisterRoute
  '/events/new': typeof EventsNewRoute
  '/apps/': typeof AppsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/partners/': typeof PartnersIndexRoute
  '/events/$id/edit': typeof EventsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps/register'
    | '/events/new'
    | '/apps/'
    | '/events/'
    | '/partners/'
    | '/events/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apps/register'
    | '/events/new'
    | '/apps'
    | '/events'
    | '/partners'
    | '/events/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/apps/register'
    | '/events/new'
    | '/apps/'
    | '/events/'
    | '/partners/'
    | '/events/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsRegisterRoute: typeof AppsRegisterRoute
  EventsNewRoute: typeof EventsNewRoute
  AppsIndexRoute: typeof AppsIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  PartnersIndexRoute: typeof PartnersIndexRoute
  EventsIdEditRoute: typeof EventsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/': {
      id: '/partners/'
      path: '/partners'
      fullPath: '/partners/'
      preLoaderRoute: typeof PartnersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/new': {
      id: '/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/register': {
      id: '/apps/register'
      path: '/apps/register'
      fullPath: '/apps/register'
      preLoaderRoute: typeof AppsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id/edit': {
      id: '/events/$id/edit'
      path: '/events/$id/edit'
      fullPath: '/events/$id/edit'
      preLoaderRoute: typeof EventsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsRegisterRoute: AppsRegisterRoute,
  EventsNewRoute: EventsNewRoute,
  AppsIndexRoute: AppsIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  PartnersIndexRoute: PartnersIndexRoute,
  EventsIdEditRoute: EventsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
